apiVersion: v1
kind: Service
metadata:
  name: helloapp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    # This matches the label in the deployment above
    app: helloapp
  ports:
    - protocol: TCP
      port: 80        # The port you visit in the browser
      targetPort: 80  # The port the container listens on
